/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QSlider *volumeSlider;
    QSlider *g1;
    QSlider *g2;
    QLabel *label;
    QLabel *label_2;
    QSlider *g3;
    QSlider *g4;
    QSlider *g5;
    QLabel *label_4;
    QSlider *g6;
    QSlider *g7;
    QSlider *g8;
    QSlider *g9;
    QSlider *g10;
    QComboBox *preset;
    QProgressBar *barra1;
    QProgressBar *barra2;
    QProgressBar *barra4;
    QProgressBar *barra3;
    QProgressBar *barra6;
    QProgressBar *barra8;
    QProgressBar *barra10;
    QProgressBar *barra5;
    QProgressBar *barra7;
    QProgressBar *barra9;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout;
    QLineEdit *fileEdit;
    QToolButton *fileButton;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_3;
    QLabel *label_12;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_28;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QMenuBar *menuBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1070, 699);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(124, 121, 127, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(186, 182, 191, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(155, 151, 159, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(62, 60, 63, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(82, 80, 84, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QBrush brush6(QColor(5, 10, 103, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush);
        QBrush brush7(QColor(0, 0, 0, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush7);
        QBrush brush8(QColor(0, 255, 0, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Link, brush8);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        QBrush brush9(QColor(255, 255, 220, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::Link, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush7);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush7);
        palette.setBrush(QPalette::Disabled, QPalette::Link, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush7);
        MainWindow->setPalette(palette);
        MainWindow->setCursor(QCursor(Qt::ArrowCursor));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        volumeSlider = new QSlider(centralWidget);
        volumeSlider->setObjectName(QStringLiteral("volumeSlider"));
        volumeSlider->setGeometry(QRect(120, 189, 20, 391));
        QPalette palette1;
        QBrush brush10(QColor(42, 182, 107, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        QBrush brush11(QColor(145, 141, 126, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        volumeSlider->setPalette(palette1);
        volumeSlider->setCursor(QCursor(Qt::ClosedHandCursor));
        volumeSlider->setMinimum(1);
        volumeSlider->setMaximum(50);
        volumeSlider->setValue(1);
        volumeSlider->setSliderPosition(1);
        volumeSlider->setOrientation(Qt::Vertical);
        volumeSlider->setTickPosition(QSlider::TicksBothSides);
        volumeSlider->setTickInterval(5);
        g1 = new QSlider(centralWidget);
        g1->setObjectName(QStringLiteral("g1"));
        g1->setGeometry(QRect(210, 189, 20, 191));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        g1->setPalette(palette2);
        g1->setCursor(QCursor(Qt::ClosedHandCursor));
        g1->setMinimum(0);
        g1->setMaximum(50);
        g1->setValue(25);
        g1->setSliderPosition(25);
        g1->setOrientation(Qt::Vertical);
        g1->setTickPosition(QSlider::TicksBothSides);
        g1->setTickInterval(5);
        g2 = new QSlider(centralWidget);
        g2->setObjectName(QStringLiteral("g2"));
        g2->setGeometry(QRect(280, 190, 20, 191));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        g2->setPalette(palette3);
        g2->setCursor(QCursor(Qt::ClosedHandCursor));
        g2->setMinimum(0);
        g2->setMaximum(50);
        g2->setSliderPosition(25);
        g2->setOrientation(Qt::Vertical);
        g2->setTickPosition(QSlider::TicksBothSides);
        g2->setTickInterval(5);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(100, 590, 59, 14));
        QPalette palette4;
        QBrush brush12(QColor(46, 52, 54, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label->setPalette(palette4);
        QFont font;
        font.setPointSize(10);
        font.setBold(true);
        font.setWeight(75);
        label->setFont(font);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(340, 390, 59, 14));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_2->setPalette(palette5);
        g3 = new QSlider(centralWidget);
        g3->setObjectName(QStringLiteral("g3"));
        g3->setGeometry(QRect(350, 190, 20, 191));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette6.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette6.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        g3->setPalette(palette6);
        g3->setCursor(QCursor(Qt::ClosedHandCursor));
        g3->setMinimum(0);
        g3->setMaximum(50);
        g3->setValue(25);
        g3->setSliderPosition(25);
        g3->setOrientation(Qt::Vertical);
        g3->setInvertedControls(false);
        g3->setTickPosition(QSlider::TicksBothSides);
        g3->setTickInterval(5);
        g4 = new QSlider(centralWidget);
        g4->setObjectName(QStringLiteral("g4"));
        g4->setGeometry(QRect(420, 189, 20, 191));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette7.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette7.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        g4->setPalette(palette7);
        g4->setCursor(QCursor(Qt::ClosedHandCursor));
        g4->setMinimum(0);
        g4->setMaximum(50);
        g4->setValue(25);
        g4->setSliderPosition(25);
        g4->setOrientation(Qt::Vertical);
        g4->setTickPosition(QSlider::TicksBothSides);
        g4->setTickInterval(5);
        g5 = new QSlider(centralWidget);
        g5->setObjectName(QStringLiteral("g5"));
        g5->setGeometry(QRect(490, 189, 20, 191));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette8.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette8.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        g5->setPalette(palette8);
        g5->setCursor(QCursor(Qt::ClosedHandCursor));
        g5->setMinimum(0);
        g5->setMaximum(50);
        g5->setValue(25);
        g5->setSliderPosition(25);
        g5->setOrientation(Qt::Vertical);
        g5->setTickPosition(QSlider::TicksBothSides);
        g5->setTickInterval(5);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(620, 390, 41, 16));
        g6 = new QSlider(centralWidget);
        g6->setObjectName(QStringLiteral("g6"));
        g6->setGeometry(QRect(560, 189, 20, 191));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette9.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette9.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        g6->setPalette(palette9);
        g6->setCursor(QCursor(Qt::ClosedHandCursor));
        g6->setMinimum(0);
        g6->setMaximum(50);
        g6->setValue(25);
        g6->setSliderPosition(25);
        g6->setOrientation(Qt::Vertical);
        g6->setTickPosition(QSlider::TicksBothSides);
        g6->setTickInterval(5);
        g7 = new QSlider(centralWidget);
        g7->setObjectName(QStringLiteral("g7"));
        g7->setGeometry(QRect(630, 190, 20, 191));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette10.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette10.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        g7->setPalette(palette10);
        g7->setCursor(QCursor(Qt::ClosedHandCursor));
        g7->setMinimum(0);
        g7->setMaximum(50);
        g7->setValue(25);
        g7->setSliderPosition(25);
        g7->setOrientation(Qt::Vertical);
        g7->setTickPosition(QSlider::TicksBothSides);
        g7->setTickInterval(5);
        g8 = new QSlider(centralWidget);
        g8->setObjectName(QStringLiteral("g8"));
        g8->setGeometry(QRect(700, 190, 20, 191));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette11.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette11.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        g8->setPalette(palette11);
        g8->setCursor(QCursor(Qt::ClosedHandCursor));
        g8->setMinimum(0);
        g8->setMaximum(50);
        g8->setValue(25);
        g8->setSliderPosition(25);
        g8->setOrientation(Qt::Vertical);
        g8->setTickPosition(QSlider::TicksBothSides);
        g8->setTickInterval(5);
        g9 = new QSlider(centralWidget);
        g9->setObjectName(QStringLiteral("g9"));
        g9->setGeometry(QRect(770, 189, 20, 191));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette12.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette12.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        g9->setPalette(palette12);
        g9->setCursor(QCursor(Qt::ClosedHandCursor));
        g9->setMinimum(0);
        g9->setMaximum(50);
        g9->setValue(25);
        g9->setSliderPosition(25);
        g9->setOrientation(Qt::Vertical);
        g9->setTickPosition(QSlider::TicksBothSides);
        g9->setTickInterval(5);
        g10 = new QSlider(centralWidget);
        g10->setObjectName(QStringLiteral("g10"));
        g10->setGeometry(QRect(840, 189, 20, 191));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette13.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette13.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        g10->setPalette(palette13);
        g10->setCursor(QCursor(Qt::ClosedHandCursor));
        g10->setMinimum(0);
        g10->setMaximum(50);
        g10->setValue(25);
        g10->setSliderPosition(25);
        g10->setOrientation(Qt::Vertical);
        g10->setTickPosition(QSlider::TicksBothSides);
        g10->setTickInterval(5);
        preset = new QComboBox(centralWidget);
        preset->setObjectName(QStringLiteral("preset"));
        preset->setGeometry(QRect(920, 201, 100, 22));
        preset->setEditable(false);
        barra1 = new QProgressBar(centralWidget);
        barra1->setObjectName(QStringLiteral("barra1"));
        barra1->setGeometry(QRect(210, 420, 16, 181));
        QPalette palette14;
        QBrush brush13(QColor(126, 126, 126, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette14.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        QBrush brush14(QColor(108, 131, 128, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette14.setBrush(QPalette::Active, QPalette::HighlightedText, brush14);
        palette14.setBrush(QPalette::Active, QPalette::Link, brush8);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette14.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette14.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush14);
        palette14.setBrush(QPalette::Inactive, QPalette::Link, brush8);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        palette14.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush14);
        palette14.setBrush(QPalette::Disabled, QPalette::Link, brush8);
        barra1->setPalette(palette14);
        barra1->setValue(24);
        barra1->setOrientation(Qt::Vertical);
        barra2 = new QProgressBar(centralWidget);
        barra2->setObjectName(QStringLiteral("barra2"));
        barra2->setGeometry(QRect(280, 420, 16, 181));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette15.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette15.setBrush(QPalette::Active, QPalette::HighlightedText, brush14);
        QBrush brush15(QColor(0, 0, 255, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::Link, brush15);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette15.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette15.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush14);
        palette15.setBrush(QPalette::Inactive, QPalette::Link, brush15);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        palette15.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush14);
        QBrush brush16(QColor(120, 255, 30, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Disabled, QPalette::Link, brush16);
        barra2->setPalette(palette15);
        barra2->setValue(24);
        barra2->setOrientation(Qt::Vertical);
        barra4 = new QProgressBar(centralWidget);
        barra4->setObjectName(QStringLiteral("barra4"));
        barra4->setGeometry(QRect(420, 420, 16, 181));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette16.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette16.setBrush(QPalette::Active, QPalette::HighlightedText, brush14);
        palette16.setBrush(QPalette::Active, QPalette::Link, brush15);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette16.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette16.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush14);
        palette16.setBrush(QPalette::Inactive, QPalette::Link, brush15);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        palette16.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush14);
        palette16.setBrush(QPalette::Disabled, QPalette::Link, brush16);
        barra4->setPalette(palette16);
        barra4->setValue(24);
        barra4->setOrientation(Qt::Vertical);
        barra3 = new QProgressBar(centralWidget);
        barra3->setObjectName(QStringLiteral("barra3"));
        barra3->setGeometry(QRect(350, 420, 16, 181));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette17.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette17.setBrush(QPalette::Active, QPalette::HighlightedText, brush14);
        palette17.setBrush(QPalette::Active, QPalette::Link, brush15);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette17.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette17.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush14);
        palette17.setBrush(QPalette::Inactive, QPalette::Link, brush15);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        palette17.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush14);
        palette17.setBrush(QPalette::Disabled, QPalette::Link, brush16);
        barra3->setPalette(palette17);
        barra3->setValue(24);
        barra3->setOrientation(Qt::Vertical);
        barra6 = new QProgressBar(centralWidget);
        barra6->setObjectName(QStringLiteral("barra6"));
        barra6->setGeometry(QRect(560, 420, 16, 181));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette18.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette18.setBrush(QPalette::Active, QPalette::HighlightedText, brush14);
        palette18.setBrush(QPalette::Active, QPalette::Link, brush15);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette18.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette18.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush14);
        palette18.setBrush(QPalette::Inactive, QPalette::Link, brush15);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        palette18.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush14);
        palette18.setBrush(QPalette::Disabled, QPalette::Link, brush16);
        barra6->setPalette(palette18);
        barra6->setValue(24);
        barra6->setOrientation(Qt::Vertical);
        barra8 = new QProgressBar(centralWidget);
        barra8->setObjectName(QStringLiteral("barra8"));
        barra8->setGeometry(QRect(700, 420, 16, 181));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette19.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette19.setBrush(QPalette::Active, QPalette::HighlightedText, brush14);
        palette19.setBrush(QPalette::Active, QPalette::Link, brush15);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette19.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette19.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush14);
        palette19.setBrush(QPalette::Inactive, QPalette::Link, brush15);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        palette19.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush14);
        palette19.setBrush(QPalette::Disabled, QPalette::Link, brush16);
        barra8->setPalette(palette19);
        barra8->setValue(24);
        barra8->setOrientation(Qt::Vertical);
        barra10 = new QProgressBar(centralWidget);
        barra10->setObjectName(QStringLiteral("barra10"));
        barra10->setGeometry(QRect(840, 420, 16, 181));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette20.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette20.setBrush(QPalette::Active, QPalette::HighlightedText, brush14);
        palette20.setBrush(QPalette::Active, QPalette::Link, brush15);
        palette20.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette20.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette20.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush14);
        palette20.setBrush(QPalette::Inactive, QPalette::Link, brush15);
        palette20.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        palette20.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush14);
        palette20.setBrush(QPalette::Disabled, QPalette::Link, brush16);
        barra10->setPalette(palette20);
        barra10->setValue(24);
        barra10->setOrientation(Qt::Vertical);
        barra5 = new QProgressBar(centralWidget);
        barra5->setObjectName(QStringLiteral("barra5"));
        barra5->setGeometry(QRect(490, 420, 16, 181));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette21.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette21.setBrush(QPalette::Active, QPalette::HighlightedText, brush14);
        palette21.setBrush(QPalette::Active, QPalette::Link, brush15);
        palette21.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette21.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette21.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush14);
        palette21.setBrush(QPalette::Inactive, QPalette::Link, brush15);
        palette21.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        palette21.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush14);
        palette21.setBrush(QPalette::Disabled, QPalette::Link, brush16);
        barra5->setPalette(palette21);
        barra5->setValue(24);
        barra5->setOrientation(Qt::Vertical);
        barra7 = new QProgressBar(centralWidget);
        barra7->setObjectName(QStringLiteral("barra7"));
        barra7->setGeometry(QRect(630, 420, 16, 181));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette22.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette22.setBrush(QPalette::Active, QPalette::HighlightedText, brush14);
        palette22.setBrush(QPalette::Active, QPalette::Link, brush15);
        palette22.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette22.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette22.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush14);
        palette22.setBrush(QPalette::Inactive, QPalette::Link, brush15);
        palette22.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        palette22.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush14);
        palette22.setBrush(QPalette::Disabled, QPalette::Link, brush16);
        barra7->setPalette(palette22);
        barra7->setValue(24);
        barra7->setOrientation(Qt::Vertical);
        barra9 = new QProgressBar(centralWidget);
        barra9->setObjectName(QStringLiteral("barra9"));
        barra9->setGeometry(QRect(770, 420, 16, 181));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::Base, brush13);
        palette23.setBrush(QPalette::Active, QPalette::Highlight, brush10);
        palette23.setBrush(QPalette::Active, QPalette::HighlightedText, brush14);
        palette23.setBrush(QPalette::Active, QPalette::Link, brush15);
        palette23.setBrush(QPalette::Inactive, QPalette::Base, brush13);
        palette23.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette23.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush14);
        palette23.setBrush(QPalette::Inactive, QPalette::Link, brush15);
        palette23.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        palette23.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush14);
        palette23.setBrush(QPalette::Disabled, QPalette::Link, brush16);
        barra9->setPalette(palette23);
        barra9->setValue(24);
        barra9->setOrientation(Qt::Vertical);
        layoutWidget = new QWidget(centralWidget);
        layoutWidget->setObjectName(QStringLiteral("layoutWidget"));
        layoutWidget->setGeometry(QRect(110, 50, 899, 49));
        horizontalLayout = new QHBoxLayout(layoutWidget);
        horizontalLayout->setSpacing(3);
        horizontalLayout->setContentsMargins(11, 11, 11, 11);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        fileEdit = new QLineEdit(layoutWidget);
        fileEdit->setObjectName(QStringLiteral("fileEdit"));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::Base, brush10);
        palette24.setBrush(QPalette::Inactive, QPalette::Base, brush10);
        palette24.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        fileEdit->setPalette(palette24);

        horizontalLayout->addWidget(fileEdit);

        fileButton = new QToolButton(layoutWidget);
        fileButton->setObjectName(QStringLiteral("fileButton"));

        horizontalLayout->addWidget(fileButton);

        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(270, 390, 59, 14));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette25.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette25.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_5->setPalette(palette25);
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(200, 390, 59, 14));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette26.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette26.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_6->setPalette(palette26);
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(410, 390, 59, 14));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette27.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette27.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_7->setPalette(palette27);
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(480, 390, 59, 14));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette28.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette28.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_8->setPalette(palette28);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(550, 390, 59, 14));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette29.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette29.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_3->setPalette(palette29);
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(630, 390, 59, 14));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette30.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette30.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_12->setPalette(palette30);
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(690, 390, 59, 14));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette31.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette31.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_9->setPalette(palette31);
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(760, 390, 59, 14));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette32.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette32.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_10->setPalette(palette32);
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(840, 390, 59, 14));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::WindowText, brush12);
        palette33.setBrush(QPalette::Inactive, QPalette::WindowText, brush12);
        palette33.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        label_11->setPalette(palette33);
        label_13 = new QLabel(centralWidget);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(0, 610, 161, 51));
        label_13->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_13->setScaledContents(true);
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(160, 610, 161, 51));
        label_14->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_14->setScaledContents(true);
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(320, 610, 161, 51));
        label_15->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_15->setScaledContents(true);
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(480, 610, 161, 51));
        label_16->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_16->setScaledContents(true);
        label_17 = new QLabel(centralWidget);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(640, 610, 161, 51));
        label_17->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_17->setScaledContents(true);
        label_18 = new QLabel(centralWidget);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(800, 610, 161, 51));
        label_18->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_18->setScaledContents(true);
        label_19 = new QLabel(centralWidget);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(960, 610, 161, 51));
        label_19->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_19->setScaledContents(true);
        label_20 = new QLabel(centralWidget);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(750, 0, 161, 51));
        label_20->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_20->setScaledContents(true);
        label_21 = new QLabel(centralWidget);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(270, 0, 161, 51));
        label_21->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_21->setScaledContents(true);
        label_22 = new QLabel(centralWidget);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(-50, 0, 161, 51));
        label_22->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_22->setScaledContents(true);
        label_23 = new QLabel(centralWidget);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(430, 0, 161, 51));
        label_23->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_23->setScaledContents(true);
        label_24 = new QLabel(centralWidget);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(590, 0, 161, 51));
        label_24->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_24->setScaledContents(true);
        label_25 = new QLabel(centralWidget);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(910, 0, 161, 51));
        label_25->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_25->setScaledContents(true);
        label_26 = new QLabel(centralWidget);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(110, 0, 161, 51));
        label_26->setPixmap(QPixmap(QString::fromUtf8("12.png")));
        label_26->setScaledContents(true);
        label_27 = new QLabel(centralWidget);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(930, 260, 81, 71));
        label_27->setPixmap(QPixmap(QString::fromUtf8("avatar.png")));
        label_27->setScaledContents(true);
        label_29 = new QLabel(centralWidget);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(20, 230, 71, 61));
        label_29->setPixmap(QPixmap(QString::fromUtf8("snow.png")));
        label_29->setScaledContents(true);
        label_30 = new QLabel(centralWidget);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(930, 500, 91, 71));
        label_30->setPixmap(QPixmap(QString::fromUtf8("christmas.png")));
        label_30->setScaledContents(true);
        label_28 = new QLabel(centralWidget);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(940, 370, 71, 71));
        label_28->setPixmap(QPixmap(QString::fromUtf8("star.png")));
        label_28->setScaledContents(true);
        label_31 = new QLabel(centralWidget);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(20, 360, 81, 61));
        label_31->setPixmap(QPixmap(QString::fromUtf8("user.png")));
        label_31->setScaledContents(true);
        label_32 = new QLabel(centralWidget);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(30, 480, 61, 61));
        label_32->setPixmap(QPixmap(QString::fromUtf8("miscellaneous.png")));
        label_32->setScaledContents(true);
        label_33 = new QLabel(centralWidget);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(50, 50, 41, 41));
        label_33->setPixmap(QPixmap(QString::fromUtf8("music.png")));
        label_33->setScaledContents(true);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1070, 22));
        MainWindow->setMenuBar(menuBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        preset->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "Volumen", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "125 Hz", Q_NULLPTR));
        label_4->setText(QString());
        preset->clear();
        preset->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "FLAT", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Clasica", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Club", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Dance", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Full Bass & Trebble", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Full Trebble", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Pop", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Reggae", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Rock", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Techno", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Zero", Q_NULLPTR)
        );
        preset->setCurrentText(QApplication::translate("MainWindow", "FLAT", Q_NULLPTR));
        fileButton->setText(QApplication::translate("MainWindow", "...", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "63 Hz", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "32 Hz", Q_NULLPTR));
        label_7->setText(QApplication::translate("MainWindow", "250 Hz", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "500 Hz", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "1 kHz", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "2 kHz", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "4 kHz", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "8 kHz", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "16 kHz", Q_NULLPTR));
        label_13->setText(QString());
        label_14->setText(QString());
        label_15->setText(QString());
        label_16->setText(QString());
        label_17->setText(QString());
        label_18->setText(QString());
        label_19->setText(QString());
        label_20->setText(QString());
        label_21->setText(QString());
        label_22->setText(QString());
        label_23->setText(QString());
        label_24->setText(QString());
        label_25->setText(QString());
        label_26->setText(QString());
        label_27->setText(QString());
        label_29->setText(QString());
        label_30->setText(QString());
        label_28->setText(QString());
        label_31->setText(QString());
        label_32->setText(QString());
        label_33->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
